name: Build and push Docker image
on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and load
        uses: docker/build-push-action@v3
        with:
          context: './app/src'
          file: ./app/Dockerfile
          tags: |
            ${{secrets.REGISTRY_URL}}/images/test-app11:latest
          labels: |
            org.opencontainers.image.description=test-app11 Docker image
      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: ${{secrets.REGISTRY_URL}}/images/app-test22:latest
          dockerfile: ./app/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: './app/src'
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{secrets.REGISTRY_URL}}/images/test-app11:latest
          labels: |
            org.opencontainers.image.description=test-app11 Docker image
